[package]
name = "rehash-codec"
version = "0.1.0"
edition = "2024"

[lib]
name = "rehashcodec"
crate-type = ["cdylib"]

[dependencies]
rehash-codec-ffi-bindings = { path = "../rehash-codec-ffi-bindings" }