[workspace]
members = [
    "rehash-desktop",
    "components/rehash-frontend",
    "components/rehash-loader",
    "components/rehash-utils",
    "components/rehash-codec",
    "components/rehash-codec-ffi-bindings"
]

resolver = "3"
