[workspace]
members = [
    "rehash-desktop",
    "components/rehash-frontend",
    "components/rehash-loader",
    "components/rehash-utils",
    "components/rehash-codec/codec",
    "components/rehash-codec/codec-ffi",
    "components/rehash-codec/codec-proc-macro"
]

resolver = "3"
