[package]
name = "rehash-codec"
version = "0.1.0"
edition = "2024"

[lib]
name = "rehashcodec"
crate-type = ["cdylib", "rlib"]

[dependencies]
rehash-codec-proc-macro = { path = "../codec-proc-macro" }
ffmpeg-next = "7.1.0"
libc = "0.2.174"
once_cell = "1.21.3"
tempfile = "3.20.0"