[package]
name = "rehash-win-installer"
version = "1.0.0"
edition = "2024"

[lib]
name = "RehashInstaller"
crate-type = ["cdylib"]


[dependencies]
reqwest = { version = "0.12.23", features = ["blocking"] }
