name: ci.yml
on:
  push:
    branches:
      - ci

jobs:
  build_rehash_front_end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Run Script
        working-directory: ./components/wasm-frontend
        run: ./build-frontend.sh

  build_rehash_loader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Run Script
        working-directory: ./components/wasm-loader
        run: ./build-loader.sh

  build_rehash_wasm_binding_lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Run Script
        working-directory: ./components/wasm-bindings-lib
        run: cargo build

  build_rehash_desktop_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt install pkg-config libssl-dev libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Run Script
        working-directory: ./components/wasm-bindings-lib
        run: cargo build

